Update build_apk.yml

diff --git a/.github/workflows/build_apk.yml b/.github/workflows/build_apk.yml
--- a/.github/workflows/build_apk.yml
+++ b/.github/workflows/build_apk.yml
@@ -1,4 +1,4 @@
-name: Build Android APK
+name: Build Flutter APK
 
 on:
   push:
@@ -25,15 +25,27 @@ jobs:
         with:
           channel: 'stable'
 
-      - name: Build Original APK
+      - name: Hard Clean Project
         run: |
           FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
           cd "$FLUTTER_DIR"
-          
           flutter clean
+          flutter pub cache clean --force
           flutter pub get
-          flutter build apk --release --android-skip-build-dependency-validation
+
+      - name: Accept Android Licences
+        run: |
+          FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
+          cd "$FLUTTER_DIR"
+          yes | flutter doctor --android-licenses || true
+
+      - name: Build APK and Copy Output
+        run: |
+          FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
+          cd "$FLUTTER_DIR"
+          flutter build apk --release --no-pub
           
+          # APK ko safe folder mein copy kar rahe hain taaki artifact upload fail na ho
           mkdir -p ../build_output
           cp build/app/outputs/flutter-apk/app-release.apk ../build_output/app-release.apk
 
